"""Parity tests for the HambergPKPD perf overhaul (#1, #3, #4 in the plan).

Each test loads a golden .npz fixture (generated by
`tests/data/_golden_fixture_generator.py` under unmodified code) and asserts
that the current code reproduces it.

Tolerance contract per the plan:
    - #3 (cache_size default) and #4 (drop np.pad/trim): math is bit-identical,
      so tolerance is `atol=rtol=1e-12`.
    - #1 (scipy.signal.lfilter rewrite): FP ops are reassociated across t, so
      we relax to `atol=rtol=1e-8`. If clip-after-lfilter diverges further for
      HambergPKPD2010, the fallback (per-compartment Python loop) tightens
      back to 1e-12 — see the plan's Step-back section.

Pre-implementation baseline run: ALL tests in this file must pass against the
current (unmodified) ReiL code at the strictest tolerance (1e-12). That proves
the fixture and the test plumbing match the production code exactly. After
each improvement lands, only the tolerance for that specific test relaxes.
"""
from __future__ import annotations

import unittest
from pathlib import Path

import numpy as np

from reil.healthcare.mathematical_models import HambergPKPD
from reil.healthcare.mathematical_models.hamberg_pkpd_2010 import HambergPKPD2010
from reil.healthcare.patient_warfarin_ravvaz import PatientWarfarinRavvaz

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

# Tolerance bands. Tighten/loosen per-test as improvements land; baseline run
# uses the strict band for every test.
STRICT_ATOL = 1e-12
STRICT_RTOL = 1e-12
LFILTER_ATOL = 1e-8
LFILTER_RTOL = 1e-8

# Must match _golden_fixture_generator.CACHE_SIZE
CACHE_SIZE = 100


def _replay(model_cls, fixture_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Re-run every patient in `fixture_path` through `model_cls`.

    Returns (computed_inr, golden_inr), each shape (n_patients, n_days+1).
    """
    f = np.load(fixture_path)
    golden = f["inr"]
    seeds = f["seeds"]
    dose_days = f["dose_days"]
    dose_vals = f["dose_vals"]
    measurement_days = f["measurement_days"].tolist()
    dose = {int(d): float(v) for d, v in zip(dose_days, dose_vals)}

    computed = np.empty_like(golden)
    for i, seed in enumerate(seeds):
        model = model_cls(cache_size=CACHE_SIZE)
        patient = PatientWarfarinRavvaz(model=model, random_seed=int(seed))
        out = patient.model(dose=dose, measurement_days=measurement_days)
        computed[i] = np.asarray(out["INR"], dtype=np.float64)
    return computed, golden


def _assert_close(testcase: unittest.TestCase, computed: np.ndarray,
                  golden: np.ndarray, atol: float, rtol: float,
                  label: str) -> None:
    if not np.allclose(computed, golden, atol=atol, rtol=rtol):
        diff = np.abs(computed - golden)
        worst = np.unravel_index(int(diff.argmax()), diff.shape)
        testcase.fail(
            f"{label}: max abs diff {diff.max():.3e} at index {worst} "
            f"(computed={computed[worst]:.12g}, golden={golden[worst]:.12g}, "
            f"atol={atol:.0e}, rtol={rtol:.0e})"
        )


class TestHambergPKPDParity(unittest.TestCase):
    """Parity vs. golden fixtures generated under unmodified ReiL code.

    Tolerance bands default to STRICT (1e-12). After each improvement lands,
    relax the band for the affected test by overriding `atol`/`rtol` here.
    """

    # --- Tolerance settings (mutable per improvement) -----------------
    # baseline run before any change: all three at STRICT.
    # after #1 lands: bump _07_atol/_07_rtol to LFILTER_* (HambergPKPD).
    # after #1 lands & HambergPKPD2010 fallback: leave _10_* at STRICT
    #   (if the per-compartment loop is the chosen path), otherwise LFILTER_*.
    # #3 + #4: leave all at STRICT (math is bit-identical).
    _07_atol = STRICT_ATOL
    _07_rtol = STRICT_RTOL
    _10_atol = STRICT_ATOL
    _10_rtol = STRICT_RTOL
    _multidose_atol = STRICT_ATOL
    _multidose_rtol = STRICT_RTOL

    def test_constant_dose_07(self) -> None:
        """200 patients × 90 days @ 5 mg/day, HambergPKPD (2007)."""
        computed, golden = _replay(
            HambergPKPD, DATA_DIR / "hamberg_pkpd_golden.npz")
        _assert_close(self, computed, golden,
                      self._07_atol, self._07_rtol,
                      "HambergPKPD constant-dose")

    def test_constant_dose_10(self) -> None:
        """200 patients × 90 days @ 5 mg/day, HambergPKPD2010.

        HambergPKPD2010's per-step `np.clip(C, 0, 1)` is non-linear; if the
        lfilter rewrite diverges past LFILTER_ATOL, fall back to the
        per-compartment Python loop (see plan's Step-back section) and keep
        this test at the strict band.
        """
        computed, golden = _replay(
            HambergPKPD2010, DATA_DIR / "hamberg_pkpd_2010_golden.npz")
        _assert_close(self, computed, golden,
                      self._10_atol, self._10_rtol,
                      "HambergPKPD2010 constant-dose")

    def test_multidose_prescribe(self) -> None:
        """50 patients × 90 days, varying schedule, HambergPKPD (2007).

        Exercises `prescribe()`'s additive path 13 times per patient — the
        primary target for #4 (drop np.pad/trim) parity. Stays at the strict
        band even after #1 because the additive arithmetic in `prescribe()`
        isn't reassociated by the lfilter rewrite.
        """
        computed, golden = _replay(
            HambergPKPD, DATA_DIR / "hamberg_pkpd_multidose_golden.npz")
        _assert_close(self, computed, golden,
                      self._multidose_atol, self._multidose_rtol,
                      "HambergPKPD multidose")


if __name__ == "__main__":
    unittest.main()
